{% set version = load_file_regex(load_file='../pyproject.toml', regex_pattern='version = "(.*)"', from_recipe_dir=True).group(1) %}

package:
    name: sqlalchemy-singlestoredb
    version: {{ version }}

source:
    path: ..

build:
    noarch: python
    number: {{ environ.get('PACKAGE_BUILD_NUMBER', '0') }}
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python {{ python }}
        - pip
    run:
        - singlestoredb
        - sqlalchemy

test:
    imports:
        - sqlalchemy_singlestoredb
    requires:
        - coverage
        - pandas
        - pytest
    commands:
        - pytest -q sqlalchemy_singlestoredb/tests/test_basics.py

about:
    home: https://github.com/singlestore-labs/sqlalchemy-singlestoredb
    license: Apache 2.0
    license_file: ../LICENSE
    summary: SingleStoreDB SQLAlchemy Dialect
    doc_url: https://sqlalchemy-singlestoredb.labs.singlestore.com/index.html
    dev_url: https://github.com/singlestore-labs/sqlalchemy-singlestoredb
